version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # Exposes the Ollama API on host
    volumes:
      - ollama-data:/root/.ollama  # Persist data for Ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"  # Exposes the Open-WebUI on port 3000 of the host
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434  # Connects to Ollama API
    volumes:
      - open-webui-data:/app/backend/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  open-webui-data:
  ollama-data:
  qdrant_storage: