services:
  index1:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    platform: linux/amd64
    environment:
      PORT: 5081
      INDEX_TYPE: serverless
      DIMENSION: 2 
      METRIC: cosine
    ports:
      - "5081:5081"
  index2:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    platform: linux/amd64
    environment:
      PORT: 5082
      INDEX_TYPE: pod
      DIMENSION: 2 
      METRIC: dot-product
    ports:
      - "5082:5082"