name: Convert Notebooks and Commit HTML

on:
  # Trigger when a pull request is merged to main or when direct updates are made to the main branch
  push:
    branches:
      - main

jobs:
  convert-and-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment for notebook conversion
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install nbconvert for converting Jupyter notebooks to HTML
      - name: Install nbconvert
        run: |
          pip install nbconvert 
          pip uninstall -y mistune
          pip install mistune==3.0.2

      # Convert all .ipynb files in the 'notebook' folder to HTML
      - name: Convert notebooks to HTML
        run: |
          mkdir -p html_output
          for file in notebook/*.ipynb; do
            echo "Converting $file to HTML"
            jupyter nbconvert --to html --output-dir html_output -- "$file"
          done

      # Ensure that the html folder exists in the repository and copy the HTML files
      - name: Copy HTML files to html folder
        run: |
          mkdir -p html   # Create html folder if it doesn't exist
          for html_file in html_output/*.html; do
            cp "$html_file" html/
          done

      # Clean up html_output directory after copying HTML files
      - name: Clean up html_output
        run: |
          rm -rf html_output/  # Remove the temporary directory

      # Commit and push the converted HTML files to the main branch
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add html/  # Only add the html directory
          
          # Check for changes and commit if there are any
          if ! git diff-index --quiet HEAD; then
            git commit -m "Convert notebooks to HTML and update html folder"
            git push origin main
          else
            echo "No changes to commit"
          fi
