name: Convert Notebooks and Commit HTML 

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-update-notebooks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install nbconvert for converting notebooks
      - name: Install nbconvert
        run: |
          pip install nbconvert

      # Convert all .ipynb files in the 'notebook' folder to HTML
      - name: Convert all notebooks to HTML
        run: |
          mkdir -p html_output
          for file in notebook/*.ipynb; do
            echo "Converting $file to HTML"
            jupyter nbconvert --to html --output-dir html_output -- "$file"
          done

      # Copy HTML files to the htmlnotebook folder without overwriting
      - name: Copy HTML files to htmlnotebook folder without overwriting
        run: |
          mkdir -p htmlnotebook
          for html_file in html_output/*.html; do
            base_html_file=$(basename "$html_file")
            if [ ! -f htmlnotebook/"$base_html_file" ]; then
              cp "$html_file" htmlnotebook/
            else
              echo "$base_html_file already exists, skipping..."
            fi
          done

      # Commit and push changes to the main branch
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git pull origin main
          git add htmlnotebook/
          git commit -m "Add new converted notebooks as HTML"
          git push origin main
