name: Build and Update Notebooks

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-update-notebooks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install nbconvert for converting notebooks
      - name: Install nbconvert
        run: |
          pip install nbconvert

      # Fetch modified .ipynb files
      - name: Get modified .ipynb files
        id: get_modified_notebooks
        run: |
          git fetch origin main
          MODIFIED_FILES=$(git diff --name-only origin/main..HEAD | grep 'notebook/.*\.ipynb' || echo "")
          echo "::set-output name=files::$MODIFIED_FILES"
          echo "Modified notebooks: $MODIFIED_FILES"

      # Convert modified .ipynb files to HTML (if any)
      - name: Convert modified notebooks to HTML
        if: steps.get_modified_notebooks.outputs.files != ''
        run: |
          mkdir -p html_output
          for file in $(git diff --name-only origin/main..HEAD | grep 'notebook/.*\.ipynb'); do
            echo "Converting $file to HTML"
            jupyter nbconvert --to html --output-dir html_output -- "$file"
          done

      # Copy HTML files to htmlnotebook folder without overwriting
      - name: Copy HTML files to htmlnotebook
        run: |
          mkdir -p htmlnotebook
          if [ -d html_output ]; then
            for html_file in html_output/*.html; do
              base_html_file=$(basename "$html_file")
              if [ ! -f htmlnotebook/"$base_html_file" ]; then
                cp "$html_file" htmlnotebook/
              else
                echo "$base_html_file already exists, skipping..."
              fi
            done
          else
            echo "No HTML files to copy."
          fi

      # Commit and push changes to the main branch
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git pull origin main
          git add htmlnotebook/
          git commit -m "Add new converted notebooks as HTML"
          git push origin main
